### ISSUE TITLE
good first contribution

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#1]
Welcome to hacktober first coders! Add to your pull request and i will see what i can do.

**Comment by sumanth-0** [comment]
Sure ! Just send me a pull request and if its below 100 lines of python
code I will accept your pull request

**Comment by ghulamhussainkhuhro** [comment]
Hi @sumanth-0 , I would like to contribute on the problems. Can you assign an issue to me...

**Comment by celinemang** [comment]
Hello, I would like to contribute to the problems. You can assign an issue to me.
