### ISSUE TITLE
Make Music Genre Classifier

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#103]
Rock or pop?
Write a program that classifies small audio files into different genres using machine learning models (you can use a pre-trained model or simple feature extraction).

**Comment by RedLordezh7Venom** [comment]
so basically an audio file will be input into the model and it will output the genre , after classifying it ? 
sounds cool can do

**Comment by RedLordezh7Venom** [comment]
can also make a gradio UI
