### ISSUE TITLE
Make Instagram Post Scheduler

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#104]
I am too busy to see social media i need help.
Create a script that posts an image with a caption to Instagram at a specified time using the Instabot API.

**Comment by RedLordezh7Venom** [comment]
wow, you can assign this to me 
but the daily post depends upon whether ur pc is on during that interval
it will automatically post during that time(event scheduler)

**Comment by Kirti-Pant** [comment]
@sumanth-0 , Can you assign me this issue?

**Comment by Kirti-Pant** [comment]
@sumanth-0 , I've uploaded my PR please do have a look
