### ISSUE TITLE
Make Random Meal Generator

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#105]
Confused again what to eat today?
Write a program that randomly selects a meal for the day by picking an appetizer, main course, and dessert from a list of options.

**Comment by MadhurSaluja** [comment]
hey can you assign me this ??

**Comment by Kirti-Pant** [comment]
hi @sumanth-0  can you assign this issue to me??

**Comment by MadhurSaluja** [comment]
@sumanth-0 I have uploaded a PR to close this issue, can you please have a look at it? :)

**Comment by Kirti-Pant** [comment]
@sumanth-0  I have uploaded my PR.
