### ISSUE TITLE
Weather App using OpenWeatherMap API

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#13]
Use api's to predict todays weather

**Comment by tasbi03** [comment]
Hey, can you assign this to me?

**Comment by tasbi03** [comment]
Hey, in contributing.md you have written Update the main README.md, adding your script to the List of Scripts in Repo, providing the script's name, a link to it, and a brief description. but I see no section to add this ?

**Comment by sumanth-0** [comment]
Hey sorry about the misinformation, I wanted the contributor's to follow it up adding it to main read.me but it was not  followed properly since many are new. You can just add a read me file in you folder of submission

**Comment by tasbi03** [comment]
Hey I have created a pull request can you check ?
