### ISSUE TITLE
Make Event Countdown Timer

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#149]
3,2,1...0 TAKE OFF!
Build a countdown timer that shows the days, hours, minutes, and seconds remaining until a specified event, such as New Year’s Eve or a personal goal.

**Comment by cherishwish** [comment]
Please assign this issue to me!

**Comment by aniruddhaadak80** [comment]
@sumanth-0, can you assign this issue to me now?
