### ISSUE TITLE
Make To-Do List with Priority Levels

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#228]
Because not all tasks are created equal.
Develop a to-do list that allows users to set priority levels (high, medium, low) and sorts tasks by priority.

**Comment by FarhadAliShaikh** [comment]
In which repository should I do this task?

**Comment by sumanth-0** [comment]
Hey @FarhadAliShaikh make a new folder with your read.me describing your project along with ur .py file into new folder and send me a pr.

**Comment by Kirti-Pant** [comment]
@sumanth-0 , can I work on this issue?
