### ISSUE TITLE
make Hangman Game

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#25]
Whats a hangman game?
Hangman is a guessing game where one player chooses a word, phrase, or sentence, and the other player attempts to guess it by suggesting letters or numbers. The player who chooses the word draws a picture of a person being hanged, adding a line for each incorrect guess. The game ends when the player who is guessing either guesses the word correctly or runs out of chance

**Comment by aniruddhaadak80** [comment]
Assign me please

**Comment by sumanth-0** [comment]
@aniruddhaadak80 if you have this code do send a pr again if the error is not coming i will accept it.
