### ISSUE TITLE
Make Number Guessing Game

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#26]
The computer generates a random number, and the player tries to guess it with hints provided.

**Comment by aniruddhaadak80** [comment]
I can work on this . Please assign me .

**Comment by Badger0909** [comment]
Hello @sumanth-0! I would like to be assigned this.

**Comment by aniruddhaadak80** [comment]
Create number-guessing.py #43 . Check please .
