### ISSUE TITLE
Make Quick Survey App

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#273]
Get the answers to life’s big (and small) questions, survey-style.
Create a simple survey tool that gathers responses from users and displays a summary of results, like average ratings or response counts.

**Comment by aniruddhaadak80** [comment]
Would you mind assigning this issue to me @sumanth-0 .Thank you .

**Comment by aniruddhaadak80** [comment]
Please assign this issue to me @sumanth-0 . Thank you .
