### ISSUE TITLE
Random Workout Generator

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#274]
Time to bulk up!
Build a workout generator that randomly suggests exercises and sets based on the user’s selected muscle groups or difficulty level.

**Comment by aniruddhaadak80** [comment]
Can you assign this issue to me @sumanth-0 . Thank you .

**Comment by shiv-0101** [comment]
Hey @sumanth-0 I could write brief workout generator below 100 lines

Let's add....
/assign to me
