### ISSUE TITLE
make Caesar Cipher Encoder/Decoder

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#29]
Encoding ,decoding what's that?
A Caesar cipher is a simple method of encoding messages. Caesar ciphers use a substitution method where letters in the alphabet are shifted by some fixed number of spaces to yield an encoding alphabet. A Caesar cipher with a shift of 1 would encode an A as a B, an M as an N, and a Z as an A, and so on.

**Comment by aniruddhaadak80** [comment]
Assign me please . I can work on this .

**Comment by RedLordezh7Venom** [comment]
I can work on Caesar hacker instead of a decoder
It basically takes a text file that has been encoded in Caesar cipher, and then gives the original file , and return the shift 
(the shift in Caesar cipher acts as the key/password)

**Comment by RedLordezh7Venom** [comment]
Can I still PR for this ?  
I've made it but didn't commit

**Comment by sumanth-0** [comment]
@RedLordezh7Venom  Sure send the PR
