### ISSUE TITLE
Make Typing Speed Test

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#33]
who is a faster coder me or you!
Create a typing test where the user types a randomly generated sentence, and the program calculates their words per minute

**Comment by aniruddhaadak80** [comment]
Assign me please . I am working on this .

**Comment by aniruddhaadak80** [comment]
Add  type_speed.py #49 for  Typing Speed Test .

**Comment by aniruddhaadak80** [comment]
Please look at #49 @sumanth-0 .
