### ISSUE TITLE
Make Password Strength Checker

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#37]
Is my password truly strong?
A tool that checks the strength of a password and gives feedback based on criteria such as length, use of symbols, numbers, and capitalization.

**Comment by shiv-0101** [comment]
python?

**Comment by Vinay8git** [comment]
Please @sumanth-0 Assign this issue to me.

**Comment by sumanth-0** [comment]
@shiv-0101 only in python and within 100 lines guys. Lets make some interesting projects

**Comment by Vinay8git** [comment]
@sumanth-0  Make Password Strength Checker #37
