### ISSUE TITLE
Issue with Colliding Folder Names

### ISSUE THREAD

**Issue by cherishwish** [sumanth-0/100LinesOfPythonCode#406]
Hi,

I am currently using this repository as a sync fork. 
However, while attempting to pull updates, I encountered an issue due to case sensitivity in folder names:
**HABIT_TRACKER/habit_tracker.py**
**Habit_Tracker/habit_tracker.py**

These two folders only differ in case, which causes a collision on case-insensitive filesystems, preventing me from successfully updating the repository.

The following warning message was displayed:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'HABIT_TRACKER/habit_tracker.py'
  'Habit_Tracker/habit_tracker.py' 
```

To resolve this issue, could you please rename one of the folders?

Thank you for your help!

**Comment by sumanth-0** [comment]
Hey @cherishwish thanks for pointing this out, try pulling the updates since i have merged the folders with duplicate names

**Comment by cherishwish** [comment]
Thanks for the quick fix!
