### ISSUE TITLE
Did anyones PR get accepted by hacktober?

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#413]
Two of my PR i had sent 1 week back was accepted today

**Comment by aniruddhaadak80** [comment]
> Two of my PR i had sent 1 week back was accepted today

Hey @sumanth-0 ,

That’s awesome 👍 to hear! 

I’m happy 😊 to share that my three pull requests were accepted during Hacktoberfest too! 

Congrats to everyone involved! 🎉

**Comment by RedLordezh7Venom** [comment]
That's awesome man, I am still anxious 
I have 6 prs in review

**Comment by Bhagy3sh** [comment]
Yea, I thank you wholeheartedly @sumanth-0 . I am glad I was able to contribute to your repo. Congrats to everyone involved as well

**Comment by aniruddhaadak80** [comment]
> Two of my PR i had sent 1 week back was accepted today

Hey @sumanth-0, have all of your PRs been accepted for `Hacktoberfest 2024` ?

**Comment by sumanth-0** [comment]
Hey @aniruddhaadak80  looks like all PR from my repo are being accepted , cause one of my revert pulls for my own repo was accepted......i wish i would have done one more for my own repo cause i am one short for completing  4 PRs. And for all who's PR was accepted from my Repo from hacktoberfest thanks for the contribution.

**Comment by sumanth-0** [comment]
The ones who is most likely to be accepted are who have contributed from first three days of this repo started
