### ISSUE TITLE
Make Pet Feeding Reminder with Alarms

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#439]
Because no one wants to be the person who forgot Fido’s dinner.
Set reminders for feeding pets, with a log for tracking meal times or special feeding instructions.

**Comment by Bhagy3sh** [comment]
Hey @sumanth-0 can u assign me this issue as well ?

**Comment by aniruddhaadak80** [comment]
Assign this issue to me please @sumanth-0 .
