### ISSUE TITLE
Make Personalized Product Price Tracker

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#446]
For bargain hunters who don’t want to check prices daily.
Track prices for specific items on e-commerce sites and alert the user when there’s a sale or discount.

**Comment by Bhagy3sh** [comment]
Hey @sumanth-0 can u assign me this issue ?

**Comment by aniruddhaadak80** [comment]
Assign this to me please @sumanth-0 .Thanks .
