### ISSUE TITLE
 Make Local Plant Care Guide

### ISSUE THREAD

**Issue by aniruddhaadak80** [sumanth-0/100LinesOfPythonCode#465]
Help your green thumb with care tips for plants.
Create a guide for indoor plants with information on ideal light, watering, and care schedules to help users maintain their greenery.

**Comment by sumanth-0** [comment]
@aniruddhaadak80  are your pr from this repo accepted?

**Comment by aniruddhaadak80** [comment]
> @aniruddhaadak80 are your pr from this repo accepted?

Yes @sumanth-0 .
