### ISSUE TITLE
Make Simple Cryptocurrency Price Tracker

### ISSUE THREAD

**Issue by sumanth-0** [sumanth-0/100LinesOfPythonCode#75]
Color of money green
Build a Python script that pulls real-time cryptocurrency data (e.g., Bitcoin, Ethereum) and displays price changes.

**Comment by aniruddhaadak80** [comment]
I can do that . Assign me please @sumanth-0 .

**Comment by yashwanthvarma18** [comment]
@sumanth-0 please assign me
